/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    CardsStack: typeof import('./src/components/cards-stack.vue')['default']
    Categories: typeof import('./src/components/categories.vue')['default']
    Chat: typeof import('./src/components/chat.vue')['default']
    FilesList: typeof import('./src/components/files-list.vue')['default']
    ItemList: typeof import('./src/components/item-list.vue')['default']
    ListBlock: typeof import('./src/components/list-block.vue')['default']
    MainMenu: typeof import('./src/components/main-menu.vue')['default']
    MenuBlock: typeof import('./src/components/menu-block.vue')['default']
    QueriesList: typeof import('./src/components/queries-list.vue')['default']
    ResultsMenu: typeof import('./src/components/results-menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsMenu: typeof import('./src/components/settings-menu.vue')['default']
    StartForm: typeof import('./src/components/start-form.vue')['default']
    Tags: typeof import('./src/components/tags.vue')['default']
    Topic: typeof import('./src/components/topic.vue')['default']
    Topics: typeof import('./src/components/topics.vue')['default']
  }
}
